### ISSUE TITLE
Wacom Intuos Pro, Wacom's Permission Error

### ISSUE THREAD

**Issue by foigus** [autopkg/jps3-recipes#13]
We are using the WacomIntuosProDriver.munki.recipe.

Wacom Intuos Pro Driver 6.3.15-1 was released on 10/8.  The 6.3.15-1 pkg appears to improper permissions with the "LaunchAgents" and "LaunchDaemons" directories (which have POSIX 644 permissions in the pkg).  While this doesn't affect the first run of WacomIntuosProDriver.munki.recipe (which obtains the 6.3.15-1 pkg and PkgPayloadUnpacker's it), subsequent WacomIntuosProDriver.munki.recipe runs die with the following:

```
PkgPayloadUnpacker
{'Input': {'destination_path': u'/Users/admin/Library/AutoPkg/Cache/local.munki.WacomIntuosProDriver/faux_root',
           'pkg_payload_path': u'/Users/admin/Library/AutoPkg/Cache/local.munki.WacomIntuosProDriver/pkgtmp/content.pkg/Payload',
           'purge_destination': True}}
Can't remove /Users/admin/Library/AutoPkg/Cache/local.munki.WacomIntuosProDriver/faux_root/Library: Permission denied
Failed.
Receipt written to /Users/admin/Library/AutoPkg/Cache/local.munki.WacomIntuosProDriver/receipts/WacomIntuosProDriver.munki-receipt-20151012-091157.plist

The following recipes failed:
    WacomIntuosProDriver.munki.recipe
        Error in local.munki.WacomIntuosProDriver: Processor: PkgPayloadUnpacker: Error: Can't remove /Users/admin/Library/AutoPkg/Cache/local.munki.WacomIntuosProDriver/faux_root/Library: Permission denied
```

chmod 755'ing the LaunchAgents and LaunchDaemons directories does allow the .munki recipe to succeed.

![screen shot 2015-10-12 at 9 15 39 am](https://cloud.githubusercontent.com/assets/5042592/10429998/362d622a-70c2-11e5-86d1-9e238c0dfa4c.png)

**Comment by jps3** [comment]
Thank you for pointing this out, those details are really helpful. (I will finally have time today to work on this.)

**Comment by jps3** [comment]
Wow, that is a mess, and is a real p.i.t.a. to fix without creating a custom AutoPkg processor. 

In the meantime, by chance have you notified Wacom of the error in the package? I will do so as well, hopefully multiple notifications will get them to release an update/fix. That would be the simplest solution.

(I will still work on this and see if I can come up with something to work around this.)

**Comment by jps3** [comment]
It is happening because: 
* Those dirs (as you pointed out) are set to 644 and not 755 in the pkg. …and…
*  Because `<key>purge_destination</key>` is set to `<true/>` in the `PkgPayloadUnpacker` Processor in the *.munki.recipe it tries to delete the contents of `faux_root` on subsequent recipe runs, and cannot because of the prior wrong permissons.

One needs to `sudo rm -fr` those dirs from `%RECIPE_CACHE_DIR%/faux_root` which is not going to happen via an AutoPkg recipe or Processor. (And would probably be a Bad Idea® as a general security concern, regardless.)

I am not seeing any obvious and simple means to "fix" these permissions at the moment, short of creating a custom processor script, and that seems stupid just for one bad pkg. Perhaps I am missing something obvious? (Still digging...)

(I have submitted a notice to Wacom using their Contact Us form about this, as I could not identify any other more direct means.)

**Comment by jps3** [comment]
The simplest "workaround," since the error is only on the AutoPkg end, looks like manually `sudo rm -fr faux_root/` from within the appropriate AutoPkg Cache subfolder (name depends on whether using local override or not).

Open to suggestions!

**Comment by foigus** [comment]
I can notify Wacom--since I'd hope to get my request and yours together, what bug report method did you use?

**Comment by jps3** [comment]
The only thing I could find to contact Wacom was via their “Contact Support” form, located here: http://www.wacom.com/en-es/support/contact-support.

(Just realizing now I probably should have saved the text I had typed into that form.)

FWIW, in past years I have never gotten any reply from Wacom Support regarding various issues/bugs with their installers, although the bugs/problems submitted eventually went away... I am quite sure I was not the only person who encountered them, or blasted them via that contact form. :-)

**Comment by jps3** [comment]
I have several fixes and updates for these recipes which will be pushed a.s.a.p. (Just a heads up.)

**Comment by jps3** [comment]
Check out  the fix. You may need to first manually clean out `%RECIPE_CACHE_DIR%/faux_root` manually before running.
