### ISSUE TITLE
SketchUpPro.munki recipe doesn't need .pkg installer

### ISSUE THREAD

**Issue by jessepeterson** [autopkg/jps3-recipes#5]
Howdy @jps3, I propose dropping the requirement on the .pkg installer for the munki recipe since it is unnecessary (Munki can install drag-drop installers) and implies an additional requirement on the autopkg administrator to run an autopkgserver when once isn't strictly required.

I'm happy to do the work if you'd accept the PR. Let me know!

**Comment by jps3** [comment]
*(My apologies for taking so long to reply, with the holidays and vacation, I got lazy about checking in on things here.)*

This will teach me to take notes. I think I had done the recipes this way because I had been having an issue with AutoPkg/Munki copying the `SketchUp *YYYY*` folder, *and* properly getting each app bundle's Info.plist information for Munki to include in it’s pkginfo file.

I’d be happy for any help/pull requests you wish to do. I try to make sure that the final Munki pkginfo file is as complete (and accurate) as possible to make sure items are deployed properly and consistently. (Nothing like the surprise gotcha weeks/months down the road because one’s assumption of how versions are checked and updates deployed to really cause a little panic. :-)
