### ISSUE TITLE
Camtasia Code Signature Changed

### ISSUE THREAD

**Issue by dcoobs** [autopkg/jps3-recipes#55]
Looks like the Camtasia code signature has changed to the following:

identifier "com.techsmith.camtasia2018" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "7TQL462TU8"

**Comment by jps3** [comment]
Thank you for pointing this out to me.

Please test this update out at your convenience. It appears to work fine for me. The delay was because I kept getting errors with the new requirements string, but it passed fine when I performed the check manually on the command line. However, once I added the strict and deep verification keys it worked fine.

**Comment by coobs1** [comment]
Yes, that seems to have done the trick. Thanks!

**Comment by dcoobs** [comment]
Yes, that seems to have done the trick. Thanks!

**Comment by jps3** [comment]
Ok. I'll close this issue then. If any problems please let me know.
