### ISSUE TITLE
 MunkiImporter Error

### ISSUE THREAD

**Issue by JMichaelAdams** [autopkg/jps3-recipes#62]
I keep getting the following error. however there is what looks like a valid .dmg in the cache. Some help would be greatly appreciated. 

Error in local.munki.WacomIntuosProDriver: Processor: MunkiImporter: Error: creating pkginfo for /Users/bs_autopkg/Library/AutoPkg/Cache/local.munki.WacomIntuosProDriver/downloads/wacom.dmg failed: Could not find a supported installer item in /Users/bs_autopkg/Library/AutoPkg/Cache/local.munki.WacomIntuosProDriver/downloads/wacom.dmg!

**Comment by jps3** [comment]
(Sorry for the delay in replying, your question just happened to fall exactly on the same day as my org's performance appraisal due date.)

To help me help you, since I am not seeing this error on my end:
1. Do you run the `local.munki.WacomIntuosProDriver` override on a regular, periodic basis (such as using AutoPkgr's scheduler or similar)?
1. If the override is run manually (and less frequently), do you know when it last successfully ran?
1. Could you attach one of the `*-receipt-*YYYYMMDD-HHMMSS.plist` receipt files from an unsuccessful run? (Additional `-v` verbose flags may help with additional debug output.)

As a general troubleshooting step with AutoPkg, I have found it often helpful to delete or rename/save the existing override, create a new one and run again. There have been a number of occasions where this has fixed a problem. (Typically due to some change in the parts of a parent recipe that get passed directly to the resulting Munki pkginfo file, and depending upon specifics may not result in an error immediately.)

**Comment by JMichaelAdams** [comment]
Response time is faster than I expected so no worries! I appreciate the help!

1. It runs once daily 
2. I am not 100% but my first record of an error is on 1/5/19
3. Here are two files. One is from it’s regular daily run the second is manually ran with -v 



J. Michael Adams
Infrastructure Support Technician
New England School of Communications
Husson University
207-992-4943
AdamsMike@Husson.edu

**Comment by jps3** [comment]
While you're gathering the receipt plist file(s), I forgot to add one additional general troubleshooting step: Check that there are no existing dmg files relating to this that are already mounted/attached (sometimes an error or bug will leave one attached after autopkg run exits). If you're comfortable with the command line `diskutil list virtual` can help identify these. (This has tripped me up more than once over time, and is worth checking.)

**Comment by jps3** [comment]
I'm not seeing any attached `*-receipt-*.plist files. (Or am just being unusually dense this afternoon.) If at all possible please attach the file(s), rather than paste the contents into a reply as text (it will be easier for me).

**Comment by JMichaelAdams** [comment]
I double checked using disk util and there are no Virtual mounted.

 I thought I attached them sorry about that. It’s almost Friday LOL


J. Michael Adams
Infrastructure Support Technician
New England School of Communications
Husson University
207-992-4943
AdamsMike@Husson.edu

**Comment by jps3** [comment]
I wanted to touch base with you and see if either the issue had (self) corrected, or if you could try attaching the `*-receipt-*.plist` files by replying directly on Github. (I'm wondering if the reply and attachments were via email if that could be part of our confusion here.) No rush, I had just circled back to this to check.

**Comment by JMichaelAdams** [comment]
Sorry I was on vaction. Here are the logs [
[wacom.zip](https://github.com/autopkg/jps3-recipes/files/2866250/wacom.zip)
](url)

**Comment by ArchchancellorMustrumRidcully** [comment]
Hi jps3,

I have inherited this (JMA's) autopkg set up and I confirmed that we have 6.3.41-2 (current) in Munki's testing pipeline, so we've pulled it down sometime along the way after this error was filed:  whatever issue JMA was having appears to be no longer an issue here.  

Along the way I have created intermediate forks and overrides, so I may have inadvertently corrected it by way of your suggestions on 1/31.

I think this is ok to close out.

Thank you and best regards,
MR
